language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

env:
  global:
  - secure: tKVDI5GcpP3utINxzYgzuwjf9JxZeQRTpGhc3bL4ZbiBFS0qhxambGUywhE2Q/zj7bmNnWyQoSDAzmDQtF6e9z+DKaqwrxhcehB2AH8R7pwGQ59ItJtt91WT3s/RvhKqV8bAnE6WfTmqyeWCR7r8czxEj3FhbKrhGHXtWoTK9nqOEGIlZjuA99NdfFJ/VPc2VWPvSqcpIJw1fO94b3lbauk6ARRajxFiZQeCIroZfwp0DoxLBAcfESw9RTCcRDgB0LuDmRGm8DvdDSo0MGgjUNtuEoaDb7tdLfFkUkztoN/u7LwPbtmC24RC4cI7cVisKApCDOvO5d9aur8pjM6TJQRqklLDSBPe2yWfdnmoOEoaIQpLcOVDrfp5YXEO53S+8fph2GSo91yCZcxByFnsOh40ZeaMSNc7H6PIrlLdm/Ji8PO1HeJS0jsLv6ovm+bKM+rm2kOvvgmDW710pTxSMSNCgezUSiBiOw8INZqPj1oLUHFwck/s/qMOhOL5bjYll6U6KYWmnt1YOJ8I3Rs3JQVfGqHOM5AiB2+3jjKWtahjVHBGMuprU5CJizNMSFe41pmoD8O4WzChhMPpLgEdTbnLooM5edUU0CJHk4v77yi47uyeGefUsjO6h0/hHKjy/HNVNCA5ePSdYdxdvAMlQVMUK2SoM0fitLupN38chw8=
  - secure: IibikVAqHdVA+i5ylDIfle3vg+4jtlJO1j0ANf8Pk6RkjpshB6c/+nBDzl/6fO8iFYNDPbqSO6sQ1HKzXiZqqbbX/M2xk0YNq915GYCJ/FdAE97buN+tMHspocSCiB8ku9JhHPcbzkyhr+mus0/cfc/AyBLTNkT+MtBF11O9UFkr9zpODRGf4Hb+CX0wfbRulEi5z3fq6Q76zbTLawQYekvWLoet6DHCrUJVVzz/zrGCzw5Xe0qDfLf+SEOuTAHU8BdDi+4LWUmdefmOpic5j/yCqrk/g731Q3bJB/ZojOugyejcpMxa5cxUyGivK7p/Aih/MaNluPH9xmZvx9a4E09RLCnlL54NaNIoFBr5lnueL0D0BFv35LGLX6WajZPWLth+cRh7biJJgy7wZJlNr6HG8jIKnwv8lHK1c5B3bx0SY0K3e3Io0ZpT3VpNUPgn/YKmWyjJxsHgUpnGyZFN3vz3FAnZAxKVDH9gyD3F897/8E9dewq0QTNrKvllSX8DximzSLBsP7lUp4E37zJE7HMuxpiWEfYAnajDyBldEGGo+Q+RERANrSoIpiPNr7cfieHI5Q1vnAwcJX9YNSH2kq4m4/UefxeY+5LNruyfdXls8rUmrcFfGdW7BmieH0SicTjbDMG3/RCh2H80lh71ZUaHiyJb+nkaFmX4AhU0Vs0=
